/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import classes.Dados;

/**
 *
 * @author rafael.valnasio
 */
public class frmPrincipal extends javax.swing.JFrame {
   private Dados msDados;
   
   public void setDados(Dados msDados){
       
   this.msDados = msDados;
   }
   
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnDesk = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArquivos = new javax.swing.JMenu();
        mnuArquivosClientes = new javax.swing.JMenuItem();
        mnuArquivosProdutos = new javax.swing.JMenuItem();
        mnuArquivosUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuArquivostSenha = new javax.swing.JMenuItem();
        mnuArquivostUsuario = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        mnuMovimentos = new javax.swing.JMenu();
        mnuMovimentosnovaVenda = new javax.swing.JMenuItem();
        mnuMovimentosRelatoriovenda = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuAjudaSobre = new javax.swing.JMenuItem();
        mnuAjudaSuporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("sistema de vendas");

        dpnDesk.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout dpnDeskLayout = new javax.swing.GroupLayout(dpnDesk);
        dpnDesk.setLayout(dpnDeskLayout);
        dpnDeskLayout.setHorizontalGroup(
            dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );
        dpnDeskLayout.setVerticalGroup(
            dpnDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        mnuArquivos.setText("Arquivos");
        mnuArquivos.setActionCommand("Arquivo");

        mnuArquivosClientes.setForeground(new java.awt.Color(102, 102, 102));
        mnuArquivosClientes.setText("Clientes");
        mnuArquivos.add(mnuArquivosClientes);

        mnuArquivosProdutos.setForeground(new java.awt.Color(102, 102, 102));
        mnuArquivosProdutos.setText("Produtos");
        mnuArquivos.add(mnuArquivosProdutos);

        mnuArquivosUsuarios.setForeground(new java.awt.Color(102, 102, 102));
        mnuArquivosUsuarios.setText("Usuários");
        mnuArquivosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArquivosUsuariosActionPerformed(evt);
            }
        });
        mnuArquivos.add(mnuArquivosUsuarios);
        mnuArquivos.add(jSeparator1);

        mnuArquivostSenha.setForeground(new java.awt.Color(102, 102, 102));
        mnuArquivostSenha.setText("Editar Senha");
        mnuArquivos.add(mnuArquivostSenha);

        mnuArquivostUsuario.setForeground(new java.awt.Color(102, 102, 102));
        mnuArquivostUsuario.setText("Editar Usuário");
        mnuArquivos.add(mnuArquivostUsuario);
        mnuArquivos.add(jSeparator2);

        jMenuItem6.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItem6.setText("SAIR");
        jMenuItem6.setToolTipText("");
        mnuArquivos.add(jMenuItem6);

        jMenuBar1.add(mnuArquivos);

        mnuMovimentos.setText("Movimento");

        mnuMovimentosnovaVenda.setForeground(new java.awt.Color(102, 102, 102));
        mnuMovimentosnovaVenda.setText("Novo Serviço");
        mnuMovimentosnovaVenda.setToolTipText("");
        mnuMovimentos.add(mnuMovimentosnovaVenda);

        mnuMovimentosRelatoriovenda.setForeground(new java.awt.Color(102, 102, 102));
        mnuMovimentosRelatoriovenda.setText("Relatorio");
        mnuMovimentosRelatoriovenda.setToolTipText("");
        mnuMovimentos.add(mnuMovimentosRelatoriovenda);

        jMenuBar1.add(mnuMovimentos);

        mnuAjuda.setText("Ajuda");

        mnuAjudaSobre.setForeground(new java.awt.Color(102, 102, 102));
        mnuAjudaSobre.setText("Sobre");
        mnuAjudaSobre.setToolTipText("");
        mnuAjuda.add(mnuAjudaSobre);

        mnuAjudaSuporte.setForeground(new java.awt.Color(102, 102, 102));
        mnuAjudaSuporte.setText("Suporte");
        mnuAjuda.add(mnuAjudaSuporte);

        jMenuBar1.add(mnuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnDesk)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnDesk)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArquivosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArquivosUsuariosActionPerformed
      frmUsuarios mUsuarios = new frmUsuarios();
      mUsuarios.setDados(msDados);
      dpnDesk.add(mUsuarios);
      mUsuarios.show();
      
      
    }//GEN-LAST:event_mnuArquivosUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnDesk;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenuItem mnuAjudaSobre;
    private javax.swing.JMenuItem mnuAjudaSuporte;
    private javax.swing.JMenu mnuArquivos;
    private javax.swing.JMenuItem mnuArquivosClientes;
    private javax.swing.JMenuItem mnuArquivosProdutos;
    private javax.swing.JMenuItem mnuArquivosUsuarios;
    private javax.swing.JMenuItem mnuArquivostSenha;
    private javax.swing.JMenuItem mnuArquivostUsuario;
    private javax.swing.JMenu mnuMovimentos;
    private javax.swing.JMenuItem mnuMovimentosRelatoriovenda;
    private javax.swing.JMenuItem mnuMovimentosnovaVenda;
    // End of variables declaration//GEN-END:variables
}
